from django.db import models

class TeamPeriod(models.Model):
    team_id = models.IntegerField()
    team_name = models.CharField(max_length=100, default='')
    period = models.IntegerField()
    state = models.CharField(max_length=100)
    fow = models.DecimalField(max_digits=5, decimal_places=2)
    sat = models.DecimalField(max_digits=5, decimal_places=1)
    blocked_shots = models.DecimalField(max_digits=5, decimal_places=1)
    goals = models.IntegerField()
    xg = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    passes = models.IntegerField()
    pass_fail = models.IntegerField()
    pass_pct = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    takeaways = models.DecimalField(max_digits=5, decimal_places=1)
    oz_takeaways = models.DecimalField(max_digits=5, decimal_places=1)
    nz_takeaways = models.DecimalField(max_digits=5, decimal_places=1)
    dz_takeaways = models.DecimalField(max_digits=5, decimal_places=1)
    lpr = models.DecimalField(max_digits=5, decimal_places=1)
    oz_lpr = models.DecimalField(max_digits=5, decimal_places=1)
    nz_lpr = models.DecimalField(max_digits=5, decimal_places=1)
    dz_lpr = models.DecimalField(max_digits=5, decimal_places=1)
    dumps = models.DecimalField(max_digits=5, decimal_places=1)
    entries = models.DecimalField(max_digits=5, decimal_places=1)
    carried_entries = models.DecimalField(max_digits=5, decimal_places=1)
    dumped_entries = models.DecimalField(max_digits=5, decimal_places=1)
    played_entries = models.DecimalField(max_digits=5, decimal_places=1)
    penalties = models.DecimalField(max_digits=5, decimal_places=1)

class ShotsPeriod(models.Model):
    team_id = models.IntegerField()
    period = models.IntegerField()
    state = models.CharField(max_length=100)
    xg = models.DecimalField(max_digits=5, decimal_places=1)
    x_coord = models.IntegerField()
    y_coord = models.IntegerField()
    shot_type = models.CharField(max_length=100)

class TeamDiff(models.Model):
    team_id = models.IntegerField()
    team_name = models.CharField(max_length=100, default='')
    goal_diff = models.IntegerField()
    state = models.CharField(max_length=100)
    fow = models.DecimalField(max_digits=5, decimal_places=2)
    sat = models.DecimalField(max_digits=5, decimal_places=1)
    blocked_shots = models.DecimalField(max_digits=5, decimal_places=1)
    goals = models.IntegerField()
    xg = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    passes = models.IntegerField()
    pass_fail = models.IntegerField()
    pass_pct = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    takeaways = models.DecimalField(max_digits=5, decimal_places=1)
    oz_takeaways = models.DecimalField(max_digits=5, decimal_places=1)
    nz_takeaways = models.DecimalField(max_digits=5, decimal_places=1)
    dz_takeaways = models.DecimalField(max_digits=5, decimal_places=1)
    lpr = models.DecimalField(max_digits=5, decimal_places=1)
    oz_lpr = models.DecimalField(max_digits=5, decimal_places=1)
    nz_lpr = models.DecimalField(max_digits=5, decimal_places=1)
    dz_lpr = models.DecimalField(max_digits=5, decimal_places=1)
    dumps = models.DecimalField(max_digits=5, decimal_places=1)
    entries = models.DecimalField(max_digits=5, decimal_places=1)
    carried_entries = models.DecimalField(max_digits=5, decimal_places=1)
    dumped_entries = models.DecimalField(max_digits=5, decimal_places=1)
    played_entries = models.DecimalField(max_digits=5, decimal_places=1)
    penalties = models.DecimalField(max_digits=5, decimal_places=1)

class ShotsGoalDiff(models.Model):
    team_id = models.IntegerField()
    goal_diff = models.IntegerField()
    state = models.CharField(max_length=100)
    xg = models.DecimalField(max_digits=5, decimal_places=1)
    x_coord = models.IntegerField()
    y_coord = models.IntegerField()
    shot_type = models.CharField(max_length=100)