# Generated by Django 5.2.6 on 2025-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShotsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('period', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('xg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('shot_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(default='', max_length=100)),
                ('goal_diff', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('fow', models.IntegerField()),
                ('sat', models.IntegerField()),
                ('blocked_shots', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('xg', models.DecimalField(decimal_places=1, default=0, max_digits=5, null=True)),
                ('passes', models.IntegerField()),
                ('pass_fail', models.IntegerField()),
                ('pass_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('takeaways', models.IntegerField()),
                ('oz_takeaways', models.IntegerField()),
                ('nz_takeaways', models.IntegerField()),
                ('dz_takeaways', models.IntegerField()),
                ('lpr', models.IntegerField()),
                ('oz_lpr', models.IntegerField()),
                ('nz_lpr', models.IntegerField()),
                ('dz_lpr', models.IntegerField()),
                ('dumps', models.IntegerField()),
                ('entries', models.IntegerField()),
                ('carried_entries', models.IntegerField()),
                ('dumped_entries', models.IntegerField()),
                ('played_entries', models.IntegerField()),
                ('penalties', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(default='', max_length=100)),
                ('period', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('fow', models.IntegerField()),
                ('sat', models.IntegerField()),
                ('blocked_shots', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('xg', models.DecimalField(decimal_places=1, default=0, max_digits=5, null=True)),
                ('passes', models.IntegerField()),
                ('pass_fail', models.IntegerField()),
                ('pass_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('takeaways', models.IntegerField()),
                ('oz_takeaways', models.IntegerField()),
                ('nz_takeaways', models.IntegerField()),
                ('dz_takeaways', models.IntegerField()),
                ('lpr', models.IntegerField()),
                ('oz_lpr', models.IntegerField()),
                ('nz_lpr', models.IntegerField()),
                ('dz_lpr', models.IntegerField()),
                ('dumps', models.IntegerField()),
                ('entries', models.IntegerField()),
                ('carried_entries', models.IntegerField()),
                ('dumped_entries', models.IntegerField()),
                ('played_entries', models.IntegerField()),
                ('penalties', models.IntegerField()),
            ],
        ),
    ]
