# Generated by Django 5.2.6 on 2025-09-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0002_alter_teamdiff_blocked_shots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdiff',
            name='fow',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teamperiod',
            name='fow',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
