# Generated by Django 5.2.6 on 2025-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0003_alter_teamdiff_fow_alter_teamperiod_fow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotsGoalDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('goal_diff', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('xg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('shot_type', models.CharField(max_length=100)),
            ],
        ),
    ]
